# Generated by Django 5.2.10 on 2026-01-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=255, unique=True)),
                ('uploader', models.CharField(max_length=255)),
                ('release_name', models.CharField(max_length=255)),
                ('album_art_url', models.URLField(max_length=500)),
                ('bandcamp_url', models.URLField(max_length=500)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
                'ordering': ['-received_at'],
            },
        ),
    ]
