# Generated by Django 5.2.10 on 2026-01-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_type',
            field=models.CharField(choices=[('ALBUM', 'Album'), ('TRACK', 'Track')], default='ALBUM', max_length=10),
        ),
    ]
