# Generated by Django 5.2.10 on 2026-02-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_release_release_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Favourite Uploader',
                'verbose_name_plural': 'Favourite Uploaders',
                'ordering': ['name'],
            },
        ),
    ]
