# Generated by Django 5.2.10 on 2026-03-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_favouriteuploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='artist',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
